### ISSUE TITLE
Implementation of new Messaging Core

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#633]
# Goal

Messaging core became obsolete, have some internal performance issues and code became too complex and need refactoring.

# Tasks

- [ ] Replace Message Statuses with read/receive dates in date list (@ex3ndr)
- [ ] Implement ConversationState + ConversationVM (@ex3ndr)
- [ ] Replace move Read/Receive states in Messages List to ConversationState (@ex3ndr)
- [ ] Remove ConversationActor and move it to new RouterActor (@ex3ndr)
- [ ] Remove DialogsActor and move it to new RouterActor (@ex3ndr)
- [ ] Reimplement Active Dialogs in RouterActor (@ex3ndr)
- [ ] Restore Notifications (@ex3ndr)
- [ ] Implement Client-side Global Counter (@ex3ndr)
- [ ] Update Android Dialog Binding (@ex3ndr)
- [ ] Update iOS Dialog Binding (@ex3ndr)
- [ ] Update Web Dialog Binding (@ex3ndr)
- [ ] Update Android Messages binding (@ex3ndr)
- [ ] Update iOS Messages binding (@ex3ndr)
- [ ] Update Web Messages binding (@nkt)

**Comment by ex3ndr** [comment]
@prettynatty @rockjam Added Counters Stripping to scheme

**Comment by ex3ndr** [comment]
Merged To master branch
