### ISSUE TITLE
Implement New iOS Push Notifications

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#634]
# Goal

Latest WhatsApp release doesn't use standard Push Notifications and use VoIP only for notifications and they use almost the same logic as android notifications. It brings us many benefits such as always predownloading messages before notification, always working notifications and instant double checkmarks.

# Tasks

- [ ] Implement New Push Notifications API (@prettynatty / @rockjam)
- [ ] Implement Unregistering Push Notifications (@ex3ndr / @prettynatty / @rockjam)
- [ ] Implement Unregistering of Push Notifications in iOS (@ex3ndr)
- [ ] Implement Registering for New notifications (@ex3ndr)

**Comment by ex3ndr** [comment]
@rockjam Updated scheme with new unregister methods.

**Comment by ex3ndr** [comment]
@prettynatty @rockjam Almost everything is done, but server doesn't send any push notification

**Comment by a7am** [comment]
The version available in AppStore sends push notifications (until not removed from recent apps, because after that there are no notifications) and also the following log is printed
`<Warning>: WARRING ACTOR_SYSTEM: Too long actor/notifications {<ACNotificationsActor_NewMessage: 0x19327d40>} in 494 ms`

But the platform version available here does not send any notifications and returns a similar warning
`<Warning>: WARRING ACTOR_SYSTEM: Too long actor/notifications {<ImActorCoreModulesNotificationsNotificationsActor_NewMessage: 0x16a2bae0>} in 365 ms`

Is this still under development? Is there any iOS version working now with push notification?
