### ISSUE TITLE
Strip out entities everywhere

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#635]
# Goal

In GetDifference we are stripping entities and app need to download manually them for missing users/groups, this dramatically reduce size of server responses, but does not implemented everywhere.

# Tasks

- [ ] [API] Import and Sync Contacts
- [ ] [Server] Import and Sync Import Contacts (@prettynatty/@rockjam)
- [ ] [Core] Import and Sync Import Contacts (@ex3ndr)
- [ ] [API] Load Dialogs / Active Dialogs
- [ ] [Server] Load Dialogs / Active Dialogs (@prettynatty/@rockjam)
- [ ] [Core] Load Dialogs / Active Dialogs (@ex3ndr)

**Comment by ex3ndr** [comment]
@prettynatty updated scheme. Waiting for your implementation.
