### ISSUE TITLE
Make Users and Groups lightweight

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#636]
# Goal

User object can contain a lot of various information and they can easily became very big. Group Object contains all members and for extra large groups it is already very big (10-s of kilobytes).

Need to be implemented after #635

# Tasks
- [ ] Design API - Add FullUser, FullGroup (@ex3ndr)
- [ ] Implement new Users and Groups on Server (@prettynatty)
- [ ] Implement async loading of FullUser/Group in Core (@ex3ndr)
- [ ] Update Android Binding
- [ ] Update iOS Binding
- [ ] Update Web Binding

**Comment by paykoob** [comment]
for adding verfied mode for users, we should add commands to actor-cli to (set and revoke verfied)

**Comment by ex3ndr** [comment]
@paykoob actor-cli is not our way. Bots are our way!

**Comment by ex3ndr** [comment]
Pushed FullUser to scheme, let's start to experiment with this.

**Comment by prettynatty** [comment]
Implemented FullUser and STRIP_ENTITIES optimizations on server
