### ISSUE TITLE
Implement Channels

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#637]
# Goal

Channels is the just group chat where only admins can post messages and very useful for broadcasting news to subscribers.

Depends on #636 

# Tasks

- [ ] [API] New Group Type - Channel (@ex3ndr)
- [ ] Implement New Channels (@prettynatty)
- [ ] Implement Channels Support in Core (@ex3ndr)
- [ ] Implement Channels in Android
- [ ] Implement Channels in iOS 
- [ ] Implement Channels in Web

**Comment by paykoob** [comment]
@ex3ndr : you implemented channel in API.
but I have a question: 
who is the author/sender of channel messages?
IMO it should be an own channel personality (e.g senderUID is group id) not real sender (one of admins of channel)
how it can be handled?
