### ISSUE TITLE
Move core-js to service worker

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#638]
# Goal

Moving core-js to service worker helps to execute messaging logic even when tab is closed, receive notifications, pre-download all messages and receive call notifications.

# Tasks

- [ ] Make POC and try to run core-js in ServiceWorker (@nkt)
- [ ] Check all `window` usage and mock everything that is required by library (@ex3ndr + @nkt)
- [ ] Make WebRTC support dynamically pluggable (@ex3ndr + @nkt)
- [ ] Enable Chrome push notifications support (already implemented, only need to be restored)
