### ISSUE TITLE
Stickers and Emoji

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#639]
# Goal

Provide people ability to send, receive and create new stickers. Add latest stickers and emojis panel to Web.

# Tasks

- [x] Show Stickers
- [x] Send Stickers
- [ ] Latest Emoji Web
- [x] Latest Emoji Android
- [ ] Latest Stickers Web
- [ ] Latest Stickers Android
- [ ] Sticker Pack Preview Core
- [ ] Sticker Pack Preview Android
- [ ] Sticker Pack Preview iOS
- [ ] Sticker Pack Preview Web
