### ISSUE TITLE
Battery Usage improvements

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#641]
# Goal

Actor Core is suitable to start/stop from push notifications and sometimes it can cause too high battery usage. Keep in mind that working in background doesn't have problems at all and 99% of power consumption come from 3G/LTE Radio module. WiFi does not consume such amount of power and can be easily be "always connected".

# Tasks

- [ ] Making network connections open only when you really need this
- [ ] Making sync only when you really need this
- [ ] Protection from too often wake-up

**Comment by ravindragit** [comment]
Can you please get this fixed or guide me how to fix this  ? All my users uninstalling the app because of this, its battery consumption is more than os in India

**Comment by sorcer1122** [comment]
I am also having issues with the battery consumption, it is beyond any adequate consumption. In such state the app is unfortunately not usable.
