### ISSUE TITLE
Search Support

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#643]
# Goal

People always need flexible search to find messages in history.

# Tasks

- [x] Implement Search on Server (enterprise only)
- [x] API Loading history from any point
- [ ] Loading History from any point in Core
- [ ] Navigation to specific message in Core
- [ ] Navigation to specific message in Web
