### ISSUE TITLE
External Availability

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#644]
# Goal

In most cases people come to actor from external URLs to join channel, open chat with someone, ask bot about something, find new sticker pack.

# Tasks

- [x] Joint to Group
- [ ] Refresh Web Design
- [ ] Write to User
- [ ] Open Sticker Pack
