### ISSUE TITLE
Miscellaneous features requests

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#656]
# Goal

Here we collect all other features and improvements. 

# Tasks

- [ ] @all and @online chat notification implementation #567 
- [ ] Create "About" option on WebApp menu. #232
- [ ] Implement wallpaper API on server #226
- [ ] More Online statuses: Online, Away, DND, etc. #206
- [ ] End-to-End crypto API #247
- [ ] Finish sticker bot implementation #197
- [ ] Add the possibility to edit your own previous messages #94

**Comment by forteller** [comment]
> Opened Web App should freeze notifications on iOS and Android

Yes! All the notifications all the time was really annoying! I hope you'll prioritize this of the ones you've added to this list. 

This service seems to be really maturing. Thank you for your work!
