### ISSUE TITLE
Block contact functionaity

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#657]
# Goal

User should be able to block other contacts. User won't get incoming messages, calls and group invites.

# Tasks
- [ ] Design API
- [ ] User should not recieve new messages from the "blocked" user on Server https://github.com/actorapp/actor-platform/issues/549
- [ ] "Block user" button in other user's profile menu on iOS https://github.com/actorapp/actor-platform/issues/557
- [ ] "Block user" button in other user's profile menu on Web App #556
- [ ] "Block user" button in other user's profile menu on Android #558

**Comment by ex3ndr** [comment]
API designed

**Comment by ex3ndr** [comment]
Implemented on Server and in Core. Have one unsolved corner case - library does sync full block list and initial blocked value might be wrong. This will be fixed in #636 .

**Comment by Maay** [comment]
Implemented in WebApp and Android
