### ISSUE TITLE
Migration to Java 8

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#672]
# Goal

Migrate to Java 8 as it provides very nice features that can reduce complexity of Actor Code

# Tasks

- [x] Switch to GWT 2.8
- [x] Switch to J2OBJC 1.0.2+
- [x] Enable retrolambda for Android libraries
- [x] Replace Anonymous classes with closures
- [ ] Extensively use Promises, improve promises support

**Comment by ex3ndr** [comment]
I am closing this tasks, but in future we should clean up our code and improve promises support in the Core
