### ISSUE TITLE
Replying messages implementation

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#689]
# Goal
Reply messages should be linked in the interface with the original ones for better chat navigation.

# Behavior
* Each message should have reply icon displayed on message hoover on the left to the love and settings icon. 
* Clicking on the symbol will autofocus to the text-message form with the @ mention of the author of the replied message in the beginning of message. 
* When reply-message is displayed in the message list it should have reply symbol (↳ for example) after the message's timestamp with the timestamp of the original message. 
* Clicking on the timestamp of the original message should autoscroll messages list to the original message. 

# Tasks
- [ ] Design API
- [ ] implement reply feature in server
- [ ] implement reply feature in sdk core
- [ ] implement reply feature in android
- [ ] implement reply feature in web
- [ ] implement reply feature in ios
