### ISSUE TITLE
Federation Support

### ISSUE THREAD

**Issue by ex3ndr** [actorapp/actor-platform#692]
# Goal

Now actor is separated from other servers and networks. For example, people often ask as if they can talk with their family from working(!) chat.

# Tasks

- [x] Pick Federation Protocol - matrix.org (@ex3ndr)
- [ ] Manual Federation between two servers
- [ ] Importing Contacts, Searching for Users
- [ ] Sending simple Text Message.

**Comment by forteller** [comment]
This is really important! Thank you for seeing this as mission critical!

But: Shouldn't Actor be compatible with XMPP/Jabber too?

**Comment by ex3ndr** [comment]
@forteller We don't want directly support obsolete federation protocols. But matrix have jabber support built in.
