### ISSUE TITLE
People invintation inhacements

### ISSUE THREAD

**Issue by Maay** [actorapp/actor-platform#741]
# Goal

User should be able easily to invite to the platform multiple contacts from his email or phone contact books.

# Tasks

## Backend
- [ ] Handle the download process of application, wait for loading of all necessary data to the chat in AppCore @ex3ndr 
- [ ] Google mail auth tokens should be stored on server
- [ ] Google mail auth tokens should be handled by AppCore @ex3ndr 
- [ ] Server should have the "send invintation by email" method

## Web App
- [ ] Handle the download process of application, wait for loading of all necessary data to the chat in Web App ()
- [ ] If user don't have any contacts, show him invite button instead of archive button in WebApp
- [ ] If user have contacts, show him invite button under the archive button in WebApp 
- [ ] After clicking on invite button google authorisation process should start in web
- [ ] After google authorisation process is successfull open fullscreen popup with the list of all the contacts  from mail accounts with avatar, fullname and email.
    - [ ] All the contacts should be marcked with checkbox
    - [ ] Clicking on te checkbox unmarked it
    - [ ] In the top of the list "invite contacts"
    - [ ] After clicking the "invite contacts" button email should be sent to all the marked contacts.
	
## Android
- [ ] Invite friends button should open the list of all contacts from the Android app.
    - [ ] All the contacts should be marcked with checkbox
    - [ ] Clicking on te checkbox unmarked it
    - [ ] In the top of the list "invite contacts"
    - [ ] After clicking the "invite contacts" button "invite by email" and "invite by sms" options should appear
    - [ ] If "invite by email" is checked, server should send the invintation email to the each checked email address
    - [ ] If "invite by sms" server should send the invintation email to the each checked email addresses

## iOS
- [ ] Invite friends button should open the list of all contacts from the iOS App.
    - [ ] All the contacts should be marcked with checkbox
    - [ ] Clicking on te checkbox unmarked it
    - [ ] In the top of the list "invite contacts"
    - [ ] After clicking the "invite contacts" button "invite by email" and "invite by sms" options should appear
    - [ ] If "invite by email" is checked, server should send the invintation email to the each checked email address
    - [ ] If "invite by sms" server should send the invintation email to the each checked email addresses
