### ISSUE TITLE
New toolbar TODO

### ISSUE THREAD

**Issue by nkt** [actorapp/actor-platform#894]
Global search:
- [x] CTRL gives focus to search
- [x] Show hint if query is empty @olegshilov
- [x] Show not found hint @olegshilov
- [x] Add hotkeys support @nkt
- [x] Remove bottom fastsearch, add hotkey to the top search @nkt 

Dialog toolbar:
- [x] Smarter call button @olegshilov 
- [x] Add tooltips @olegshilov 
- [x] Show text search results as messages
- [x] Hide call button in big groups @nkt 
- [x] Fix the display of discover screen @olegshilov 
- [x] Add photos @olegshilov 
- [ ] Add links
- [ ] Add documents
